apiVersion: v1
kind: Service
metadata:
  labels: {}
  name: {{ .Values.appName }}-app
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: {{ .Values.internalPort }}-tcp
    port: {{ .Values.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.internalPort }}
  sessionAffinity: None
  type: ClusterIP
